[package]
name = "test"
version = "2.1.1"
description = "Motoko testing library to run tests with mops"
repository = "https://github.com/ZenVoich/test"
keywords = [ "test", "testing", "unit", "suite", "expect", "matchers", "mops" ]
license = "MIT"

[dependencies]
base = "0.14.5"

[toolchain]
moc = "0.11.1"
wasmtime = "19.0.0"

[requirements]
moc = "0.11.0"