[package]
name = "test"
version = "1.0.1"
description = "Motoko testing library to run tests with mops"
repository = "https://github.com/ZenVoich/test"
keywords = [ "test", "mops", "testing", "unit", "suite" ]
license = "MIT"

[dependencies]
base = "0.8.1"